#### general settings
name: blur_allscale
use_tb_logger: true
model: corr_EncDec
distortion: sr
scale: 4
gpu_ids: [4]
step: 1
kernel_size: 21
code_length: 10
sig_min: 0.2
sig_max: 3.0
sig: 2.6

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGTker
    dataroot_GT: ../../Asfand/HR/Train_HR
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 8
    GT_size: 256
    LR_size: 64
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: DIV2K
    mode: LQGTker
    dataroot_GT: ../../Asfand/HR/Val_HR_BSD68
    dataroot_LQ: ~

#### network structures
network_G:
  which_model_G: Corr_EncDec
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 4
  code_length: 10

#### path
path:
  #pretrain_model_G: ../checkpoints/456_P.pth
  #pretrain_model_G: ../checkpoints/latest_Pker_68000.pth
  #pretrain_model_G: ../experiments/initializer_models/initializer_models/60000_G.pth
  pretrain_model_G: ~
  strict_load: true
  #resume_state: ../experiments/blur_sc1_ker2/training_state/2500.state
  resume_state: ~
  
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: ~
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: ~ #[250000, 250000, 250000, 250000]
  restarts: ~ #[250000, 500000, 750000]
  restart_weights: ~ #[1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l2
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: 2000 #!!float 5e3

#### logger
logger:
  print_freq: 500
  save_checkpoint_freq: 2000
